/* eslint-disable */
export default [
  [
    {
      title: '安全带',
      children: [
        { title: '单背安全带', href: '/category/1/1' },
        { title: '电工安全带', href: '/category/1/2' },
        { title: '双背安全带', href: '/category/1/3' },
      ],
    },
    {
      title: '安全帽',
      children: [
        { title: '玻璃钢安全帽', href: '/category/2/1' },
        { title: '塑料安全帽', href: '/category/2/2' },
      ],
    },
    {
      title: '厨房用具',
      children: [
        { title: '柜子', href: '/category/3/1' },
        { title: '容器', href: '/category/3/2' },
        { title: '桌子', href: '/category/3/3' },
        { title: '其他厨房用品', href: '/category/3/4' },
        { title: '电器', href: '/category/3/5' },
      ],
    },
    {
      title: '防护用品',
      children: [
        { title: '布手套', href: '/category/4/1' },
        { title: '电焊手套', href: '/category/4/2' },
        { title: '耳塞', href: '/category/4/3' },
        { title: '防砸鞋', href: '/category/4/4' },
        { title: '挂胶手套', href: '/category/4/5' },
        { title: '绝缘手套', href: '/category/4/6' },
        { title: '劳保鞋', href: '/category/4/7' },
        { title: '面具', href: '/category/4/8' },
        { title: '皮手套', href: '/category/4/9' },
        { title: '乳胶手套', href: '/category/4/10' },
        { title: '眼镜', href: '/category/4/11' },
        { title: '雨鞋', href: '/category/4/12' },
        { title: '口罩', href: '/category/4/13' },
      ],
    },
    {
      title: '劳保工作服',
      children: [
        { title: '大褂', href: '/category/5/1' },
        { title: '电焊服', href: '/category/5/2' },
        { title: '棉衣', href: '/category/5/3' },
        { title: '雨衣', href: '/category/5/4' },
        { title: '工作服', href: '/category/5/5' },
      ],
    },
    {
      title: '日杂用品',
      children: [
        { title: '减速带', href: '/category/6/1' },
        { title: '保温桶', href: '/category/6/2' },
        { title: '草帘被', href: '/category/6/3' },
        { title: '车圈', href: '/category/6/4' },
        { title: '车轴', href: '/category/6/5' },
        { title: '床', href: '/category/6/6' },
        { title: '镐', href: '/category/6/7' },
        { title: '工业毛毡', href: '/category/6/8' },
        { title: '锅壶', href: '/category/6/9' },
        { title: '灰斗', href: '/category/6/10' },
        { title: '洁厕灵', href: '/category/6/11' },
        { title: '流体管', href: '/category/6/12' },
        { title: '麻袋', href: '/category/6/13' },
        { title: '麻绳', href: '/category/6/14' },
        { title: '毛巾', href: '/category/6/15' },
        { title: '帽子', href: '/category/6/16' },
        { title: '美纹纸', href: '/category/6/17' },
        { title: '门帘', href: '/category/6/18' },
        { title: '棉丝', href: '/category/6/19' },
        { title: '牛皮纸', href: '/category/6/20' },
        { title: '喷雾器', href: '/category/6/21' },
        { title: '盆斗', href: '/category/6/22' },
        { title: '旗', href: '/category/6/23' },
        { title: '汽油桶', href: '/category/6/24' },
        { title: '锹', href: '/category/6/25' },
        { title: '日用其他', href: '/category/6/26' },
        { title: '日用桶', href: '/category/6/27' },
        { title: '伞', href: '/category/6/28' },
        { title: '扫帚', href: '/category/6/29' },
        { title: '上车', href: '/category/6/30' },
        { title: '透明皂', href: '/category/6/31' },
        { title: '拖布', href: '/category/6/32' },
        { title: '洗涤灵', href: '/category/6/33' },
        { title: '洗衣粉', href: '/category/6/34' },
        { title: '洗衣液', href: '/category/6/35' },
        { title: '下车', href: '/category/6/36' },
        { title: '线麻', href: '/category/6/37' },
        { title: '消毒液', href: '/category/6/38' },
        { title: '袖章', href: '/category/6/39' },
        { title: '油麻', href: '/category/6/40' },
        { title: '增强管', href: '/category/6/41' },
        { title: '障碍帽', href: '/category/6/42' },
        { title: '胶带', href: '/category/6/43' },
        { title: '其他厨房用品', href: '/category/6/44' },
        { title: '垃圾桶', href: '/category/6/45' },
      ],
    },
    {
      title: '绳网',
      children: [
        { title: '工地防护栏', href: '/category/7/1' },
        { title: '尼龙绳', href: '/category/7/2' },
        { title: '塑料绳', href: '/category/7/3' },
        { title: '小线', href: '/category/7/4' },
        { title: '遮阳网', href: '/category/7/5' },
        { title: '防尘网', href: '/category/7/6' },
        { title: '安全网', href: '/category/7/7' },
      ],
    },
    {
      title: '塑料布、土工布、帐篷',
      children: [
        { title: '地膜', href: '/category/8/1' },
        { title: '彩条布', href: '/category/8/2' },
        { title: '排水板/土工布', href: '/category/8/3' },
        { title: '苫布', href: '/category/8/4' },
        { title: '塑料布', href: '/category/8/5' },
        { title: '帐篷', href: '/category/8/6' },
        { title: '拉伸膜', href: '/category/8/7' },
      ],
    },
    {
      title: '梯子',
      children: [
        { title: '关节梯', href: '/category/9/1' },
        { title: '人字梯', href: '/category/9/2' },
      ],
    },
    { title: '零星材料', children: [{ title: '零星材料', href: '/category/10/1' }] },
    { title: '手推车', children: [{ title: '整车', href: '/category/11/1' }] },
  ],
  [
    {
      title: 'PE给水',
      children: [
        { title: 'PE-RT地暖管', href: '/category/1/1' },
        { title: 'PE法兰盘', href: '/category/1/2' },
        { title: 'PE给水电熔套管', href: '/category/1/3' },
        { title: 'PE给水管', href: '/category/1/4' },
        { title: 'PE给水内螺纹直接头', href: '/category/1/5' },
        { title: 'PE给水三通', href: '/category/1/6' },
        { title: 'PE给水外螺纹直接头', href: '/category/1/7' },
        { title: 'PE给水弯头', href: '/category/1/8' },
        { title: 'PE给水异径套', href: '/category/1/9' },
        { title: 'PE给水直通', href: '/category/1/10' },
        { title: 'PE管帽', href: '/category/1/11' },
      ],
    },
    {
      title: 'PPR管件',
      children: [
        { title: 'PPR堵头', href: '/category/2/1' },
        { title: 'PPR管', href: '/category/2/2' },
        { title: 'PPR管卡', href: '/category/2/3' },
        { title: 'PPR过桥', href: '/category/2/4' },
        { title: 'PPR活接', href: '/category/2/5' },
        { title: 'PPR截止阀', href: '/category/2/6' },
        { title: 'PPR内牙三通', href: '/category/2/7' },
        { title: 'PPR内牙弯头', href: '/category/2/8' },
        { title: 'PPR内牙直接', href: '/category/2/9' },
        { title: 'PPR球阀', href: '/category/2/10' },
        { title: 'PPR三通', href: '/category/2/11' },
        { title: 'PPR外牙弯头', href: '/category/2/12' },
        { title: 'PPR外牙直接', href: '/category/2/13' },
        { title: 'PPR弯头', href: '/category/2/14' },
        { title: 'PPR异径套', href: '/category/2/15' },
        { title: 'PPR直接', href: '/category/2/16' },
        { title: '热熔器', href: '/category/2/17' },
        { title: '铁管卡', href: '/category/2/18' },
      ],
    },
    {
      title: 'PVC给排水',
      children: [
        { title: 'PVC-U给排水直接', href: '/category/3/1' },
        { title: 'PVC-U排水管', href: '/category/3/2' },
        { title: 'PVC给水H型管', href: '/category/3/3' },
        { title: 'PVC给水垫片', href: '/category/3/4' },
        { title: 'PVC给水法兰', href: '/category/3/5' },
        { title: 'PVC给水管', href: '/category/3/6' },
        { title: 'PVC给水胶水', href: '/category/3/7' },
        { title: 'PVC给水接头', href: '/category/3/8' },
        { title: 'PVC给水球阀', href: '/category/3/9' },
        { title: 'PVC给水三通', href: '/category/3/10' },
        { title: 'PVC给水四通', href: '/category/3/11' },
        { title: 'PVC给水弯头', href: '/category/3/12' },
        { title: 'PVC胶水', href: '/category/3/13' },
        { title: 'PVC排水存水弯', href: '/category/3/14' },
        { title: 'PVC排水大便接口', href: '/category/3/15' },
        { title: 'PVC排水地漏', href: '/category/3/16' },
        { title: 'PVC排水管', href: '/category/3/17' },
        { title: 'PVC排水管卡', href: '/category/3/18' },
        { title: 'PVC排水检查口', href: '/category/3/19' },
        { title: 'PVC排水胶水', href: '/category/3/20' },
        { title: 'PVC排水接头', href: '/category/3/21' },
        { title: 'PVC排水清扫口', href: '/category/3/22' },
        { title: 'PVC排水三通', href: '/category/3/23' },
        { title: 'PVC排水伸缩节', href: '/category/3/24' },
        { title: 'PVC排水四通', href: '/category/3/25' },
        { title: 'PVC排水透气帽', href: '/category/3/26' },
        { title: 'PVC排水弯头', href: '/category/3/27' },
        { title: 'PVC排水止水环', href: '/category/3/28' },
        { title: 'PVC排水雨水斗', href: '/category/3/29' },
        { title: '灰管', href: '/category/3/30' },
      ],
    },
    {
      title: '井盖篦子',
      children: [
        { title: '不锈钢篦子', href: '/category/4/1' },
        { title: '承插式哈夫节', href: '/category/4/2' },
        { title: '防滑卡古', href: '/category/4/3' },
        { title: '复合井盖', href: '/category/4/4' },
        { title: '井盖', href: '/category/4/5' },
        { title: '球墨井盖', href: '/category/4/6' },
        { title: '塑料检查井', href: '/category/4/7' },
      ],
    },
    {
      title: '铝塑管件',
      children: [
        { title: '铝塑管', href: '/category/5/1' },
        { title: '铝塑管（冷）', href: '/category/5/2' },
        { title: '铝塑管（热）', href: '/category/5/3' },
        { title: '铝塑管管扣', href: '/category/5/4' },
        { title: '铝塑管剪刀', href: '/category/5/5' },
        { title: '铝塑管三通', href: '/category/5/6' },
        { title: '铝塑管弯管簧', href: '/category/5/7' },
        { title: '铝塑管弯头', href: '/category/5/8' },
        { title: '铝塑管直通', href: '/category/5/9' },
      ],
    },
    {
      title: '双壁波纹管',
      children: [
        { title: 'HDPE双壁波纹管', href: '/category/6/1' },
        { title: 'HDPE双壁波纹管胶圈', href: '/category/6/2' },
      ],
    },
    {
      title: '铸铁管件',
      children: [
        { title: 'AW型地平', href: '/category/7/1' },
        { title: 'A型管件大小头', href: '/category/7/2' },
        { title: 'A型管件返水弯', href: '/category/7/3' },
        { title: 'A型管件检查口', href: '/category/7/4' },
        { title: 'A型管件盲堵', href: '/category/7/5' },
        { title: 'A型管件三通', href: '/category/7/6' },
        { title: 'A型管件四通', href: '/category/7/7' },
        { title: 'A型管件套袖', href: '/category/7/8' },
        { title: 'A型管件透气管', href: '/category/7/9' },
        { title: 'A型管件弯头', href: '/category/7/10' },
        { title: 'A型管件压盖', href: '/category/7/11' },
        { title: 'A型胶圈', href: '/category/7/12' },
        { title: 'A型铸铁管', href: '/category/7/13' },
        { title: 'W型返水弯', href: '/category/7/14' },
        { title: 'W型检查口', href: '/category/7/15' },
        { title: 'W型盲堵', href: '/category/7/16' },
        { title: 'W型弯头', href: '/category/7/17' },
        { title: 'W型下水管', href: '/category/7/18' },
        { title: '不锈钢管束', href: '/category/7/19' },
        { title: '喉箍', href: '/category/7/20' },
        { title: '球墨管件', href: '/category/7/21' },
        { title: 'W型铸铁管', href: '/category/7/22' },
        { title: 'B型铸铁管', href: '/category/7/23' },
      ],
    },
    { title: '其他管件', children: [{ title: '其他排水', href: '/category/8/1' }] },
  ],
  [
    {
      title: '电线、电缆',
      children: [
        { title: 'BLV电线', href: '/category/1/1' },
        { title: 'YJV电线', href: '/category/1/2' },
        { title: '电缆盘', href: '/category/1/3' },
        { title: '电力电缆', href: '/category/1/4' },
        { title: '焊把线', href: '/category/1/5' },
        { title: '护套线', href: '/category/1/6' },
        { title: '控制电缆', href: '/category/1/7' },
        { title: '耐火塑铜线', href: '/category/1/8' },
        { title: '耐火双绞线', href: '/category/1/9' },
        { title: '平行线', href: '/category/1/10' },
        { title: '屏蔽电缆', href: '/category/1/11' },
        { title: '塑铜电缆', href: '/category/1/12' },
        { title: '塑铜线', href: '/category/1/13' },
        { title: '通讯线', href: '/category/1/14' },
        { title: '橡胶电缆', href: '/category/1/15' },
        { title: '阻燃塑铜线', href: '/category/1/16' },
        { title: '阻燃双绞线', href: '/category/1/17' },
      ],
    },
    {
      title: '低压电器',
      children: [
        { title: '按钮开关', href: '/category/2/1' },
        { title: '保险', href: '/category/2/2' },
        { title: '保险丝', href: '/category/2/3' },
        { title: '刀闸', href: '/category/2/4' },
        { title: '倒顺开关', href: '/category/2/5' },
        { title: '工业风扇', href: '/category/2/6' },
        { title: '行程开关', href: '/category/2/7' },
        { title: '机械开关', href: '/category/2/8' },
        { title: '家用风扇', href: '/category/2/9' },
        { title: '接触器', href: '/category/2/10' },
        { title: '开水器', href: '/category/2/11' },
        { title: '空开', href: '/category/2/12' },
        { title: '漏电', href: '/category/2/13' },
        { title: '稳压器', href: '/category/2/14' },
        { title: '线圈', href: '/category/2/15' },
        { title: '浴霸', href: '/category/2/16' },
        { title: '转换开关', href: '/category/2/17' },
        { title: '组合开关', href: '/category/2/18' },
        { title: '继电器', href: '/category/2/19' },
        { title: '互感器', href: '/category/2/20' },
        { title: '信号灯', href: '/category/2/21' },
      ],
    },
    {
      title: '电气仪表',
      children: [
        { title: '测试仪', href: '/category/3/1' },
        { title: '电度表', href: '/category/3/2' },
        { title: '电压表', href: '/category/3/3' },
        { title: '风速表', href: '/category/3/4' },
        { title: '钳形表', href: '/category/3/5' },
        { title: '万用表', href: '/category/3/6' },
        { title: '验电器', href: '/category/3/7' },
        { title: '摇表', href: '/category/3/8' },
      ],
    },
    {
      title: '开关插座',
      children: [
        { title: '插头', href: '/category/4/1' },
        { title: '电视插头', href: '/category/4/2' },
        { title: '电视分配器', href: '/category/4/3' },
        { title: '工业插头', href: '/category/4/4' },
        { title: '功能面板', href: '/category/4/5' },
        { title: '轨道插座', href: '/category/4/6' },
        { title: '面板开关', href: '/category/4/7' },
        { title: '聚乙烯管', href: '/category/4/8' },
        { title: '其他开关', href: '/category/4/9' },
        { title: '墙壁插座', href: '/category/4/10' },
        { title: '声光控开关', href: '/category/4/11' },
        { title: '线缆接头', href: '/category/4/12' },
        { title: '插座', href: '/category/4/13' },
      ],
    },
    { title: '插线板', children: [{ title: '插座', href: '/category/5/1' }] },
    {
      title: '接线盒/盖',
      children: [
        { title: '电表箱', href: '/category/6/1' },
        { title: '塑料线盒', href: '/category/6/2' },
        { title: '铁盖板', href: '/category/6/3' },
        { title: '线槽', href: '/category/6/4' },
        { title: '铸铝线盒', href: '/category/6/5' },
        { title: '铁线盒', href: '/category/6/6' },
      ],
    },
    {
      title: '穿线管/件',
      children: [
        { title: 'GB/T穿线管', href: '/category/7/1' },
        { title: '穿线管配件', href: '/category/7/2' },
        { title: '电缆接头', href: '/category/7/3' },
        { title: '吊卡', href: '/category/7/4' },
        { title: '根母', href: '/category/7/5' },
        { title: '接头', href: '/category/7/6' },
        { title: '预应力波纹管', href: '/category/7/7' },
        { title: '元宝卡', href: '/category/7/8' },
        { title: '包塑穿线管', href: '/category/7/9' },
        { title: '龙骨卡', href: '/category/7/10' },
      ],
    },
    {
      title: 'PVC穿线管',
      children: [
        { title: 'PVC穿线管管件', href: '/category/8/1' },
        { title: '增强管', href: '/category/8/2' },
      ],
    },
    {
      title: '绝缘塑料',
      children: [
        { title: '热缩管', href: '/category/9/1' },
        { title: '标示管', href: '/category/9/2' },
        { title: '缠绕管', href: '/category/9/3' },
        { title: '环氧板', href: '/category/9/4' },
        { title: '黄腊管', href: '/category/9/5' },
        { title: '灰板', href: '/category/9/6' },
        { title: '警示胶带', href: '/category/9/7' },
        { title: '尼龙棒', href: '/category/9/8' },
        { title: '塑料胶布', href: '/category/9/9' },
        { title: '五指套', href: '/category/9/10' },
        { title: '终端接头', href: '/category/9/11' },
      ],
    },
    {
      title: '接线端子',
      children: [
        { title: '瓷端子', href: '/category/10/1' },
        { title: '端子', href: '/category/10/2' },
        { title: '接线鼻子', href: '/category/10/3' },
        { title: '绝缘子', href: '/category/10/4' },
        { title: '开口鼻子', href: '/category/10/5' },
        { title: '冷压鼻子', href: '/category/10/6' },
        { title: '引进鼻子', href: '/category/10/7' },
      ],
    },
    {
      title: '电料辅料',
      children: [
        { title: '标盘', href: '/category/11/1' },
        { title: '波纹穿线管', href: '/category/11/2' },
        { title: '电笔', href: '/category/11/3' },
        { title: '电铃', href: '/category/11/4' },
        { title: '吊盒', href: '/category/11/5' },
        { title: '铁绑线', href: '/category/11/6' },
        { title: '吸盘', href: '/category/11/7' },
        { title: '线卡', href: '/category/11/8' },
        { title: '压线帽', href: '/category/11/9' },
        { title: '扎带', href: '/category/11/10' },
      ],
    },
    {
      title: '并勾/线夹',
      children: [
        { title: '铜接地排', href: '/category/12/1' },
        { title: '线夹', href: '/category/12/2' },
        { title: '铜接地带', href: '/category/12/3' },
      ],
    },
    {
      title: '线槽',
      children: [
        { title: 'PVC线槽管件', href: '/category/13/1' },
        { title: '地槽', href: '/category/13/2' },
        { title: '电缆桥架配件', href: '/category/13/3' },
      ],
    },
    {
      title: '电力金具',
      children: [
        { title: '直瓶', href: '/category/14/1' },
        { title: 'U型抱古', href: '/category/14/2' },
        { title: '瓷珠', href: '/category/14/3' },
        { title: '尖铁板', href: '/category/14/4' },
        { title: '脚扣带', href: '/category/14/5' },
        { title: '曲拉板', href: '/category/14/6' },
        { title: '弯头', href: '/category/14/7' },
        { title: '地线钎子', href: '/category/14/8' },
        { title: '垫铁', href: '/category/14/9' },
        { title: '角担', href: '/category/14/10' },
        { title: '拉台', href: '/category/14/11' },
        { title: '拉线抱古', href: '/category/14/12' },
        { title: '拉线棍', href: '/category/14/13' },
      ],
    },
    {
      title: '其他辅材',
      children: [
        { title: '避雷卡针', href: '/category/15/1' },
        { title: '充电机', href: '/category/15/2' },
        { title: '瓷砖卡子', href: '/category/15/3' },
        { title: '导电膏', href: '/category/15/4' },
        { title: '电表盘', href: '/category/15/5' },
        { title: '电池', href: '/category/15/6' },
        { title: '电磁阀', href: '/category/15/7' },
        { title: '管堵', href: '/category/15/8' },
        { title: '护口', href: '/category/15/9' },
        { title: '铅块', href: '/category/15/10' },
        { title: '锡膏', href: '/category/15/11' },
        { title: '锡锅', href: '/category/15/12' },
        { title: '锡丝', href: '/category/15/13' },
        { title: '锡条', href: '/category/15/14' },
        { title: '蓄电池', href: '/category/15/15' },
        { title: '元木', href: '/category/15/16' },
      ],
    },
    { title: '焊接设备、工具及耗材', children: [{ title: '焊接辅件', href: '/category/16/1' }] },
    { title: '配电照明箱', children: [{ title: '照明箱', href: '/category/17/1' }] },
  ],
  [
    {
      title: '玛钢管件',
      children: [
        { title: '补芯', href: '/category/1/1' },
        { title: '对丝', href: '/category/1/2' },
        { title: '管堵', href: '/category/1/3' },
        { title: '管箍', href: '/category/1/4' },
        { title: '过桥', href: '/category/1/5' },
        { title: '三通', href: '/category/1/6' },
        { title: '四通', href: '/category/1/7' },
        { title: '弯头', href: '/category/1/8' },
      ],
    },
    {
      title: '沟槽管件',
      children: [
        { title: '沟槽大小头', href: '/category/2/1' },
        { title: '沟槽堵头', href: '/category/2/2' },
        { title: '沟槽法兰', href: '/category/2/3' },
        { title: '沟槽法兰短管', href: '/category/2/4' },
        { title: '沟槽机械三通', href: '/category/2/5' },
        { title: '沟槽机械四通', href: '/category/2/6' },
        { title: '沟槽接头弯头', href: '/category/2/7' },
        { title: '沟槽三通', href: '/category/2/8' },
        { title: '沟槽四通', href: '/category/2/9' },
      ],
    },
    {
      title: '钢塑管件',
      children: [
        { title: '钢塑对丝', href: '/category/3/1' },
        { title: '钢塑管箍', href: '/category/3/2' },
        { title: '钢塑三通四通', href: '/category/3/3' },
        { title: '钢塑弯头', href: '/category/3/4' },
      ],
    },
    {
      title: '铜阀门',
      children: [
        { title: '铜截止阀', href: '/category/4/1' },
        { title: '分水器', href: '/category/4/2' },
        { title: '铜浮球阀', href: '/category/4/3' },
        { title: '铜过滤器', href: '/category/4/4' },
        { title: '铜排气阀', href: '/category/4/5' },
        { title: '铜平衡阀', href: '/category/4/6' },
        { title: '铜球阀', href: '/category/4/7' },
        { title: '铜温控阀', href: '/category/4/8' },
        { title: '铜闸阀', href: '/category/4/9' },
        { title: '铜止回阀', href: '/category/4/10' },
        { title: '温控器', href: '/category/4/11' },
        { title: '旋塞', href: '/category/4/12' },
        { title: '铜减压阀', href: '/category/4/13' },
      ],
    },
    {
      title: '铸铁阀门',
      children: [
        { title: '铸铁底阀', href: '/category/5/1' },
        { title: '铸铁蝶阀', href: '/category/5/2' },
        { title: '铸铁过滤器', href: '/category/5/3' },
        { title: '铸铁截止阀', href: '/category/5/4' },
        { title: '铸铁排污阀', href: '/category/5/5' },
        { title: '铸铁平衡阀', href: '/category/5/6' },
        { title: '铸铁球阀', href: '/category/5/7' },
        { title: '铸铁调节阀', href: '/category/5/8' },
        { title: '铸铁蜗轮蝶阀', href: '/category/5/9' },
        { title: '铸铁闸阀', href: '/category/5/10' },
        { title: '铸铁止回阀', href: '/category/5/11' },
        { title: '铸铁柱塞阀', href: '/category/5/12' },
      ],
    },
    {
      title: '铸钢阀门',
      children: [
        { title: '重型铸钢阀门', href: '/category/6/1' },
        { title: '铸钢蝶阀', href: '/category/6/2' },
        { title: '铸钢过滤器', href: '/category/6/3' },
        { title: '铸钢截止阀', href: '/category/6/4' },
        { title: '铸钢球阀', href: '/category/6/5' },
        { title: '铸钢闸阀', href: '/category/6/6' },
        { title: '铸钢止回阀', href: '/category/6/7' },
        { title: '铸钢柱塞阀', href: '/category/6/8' },
      ],
    },
    {
      title: '法兰盘',
      children: [
        { title: '蝶阀法兰盘', href: '/category/7/1' },
        { title: '镀锌丝扣法兰盘', href: '/category/7/2' },
        { title: '锻钢法兰盘', href: '/category/7/3' },
        { title: '锻钢盲板', href: '/category/7/4' },
        { title: '专用法兰盘', href: '/category/7/5' },
      ],
    },
    {
      title: '测量仪表',
      children: [
        { title: '温度计', href: '/category/8/1' },
        { title: '压力表', href: '/category/8/2' },
      ],
    },
    {
      title: '管卡',
      children: [
        { title: '标准吊卡', href: '/category/9/1' },
        { title: '镀锌单管卡子', href: '/category/9/2' },
        { title: '镀锌双管卡子', href: '/category/9/3' },
        { title: '万能吊卡', href: '/category/9/4' },
      ],
    },
    {
      title: '橡胶垫片',
      children: [
        { title: '法兰垫', href: '/category/10/1' },
        { title: '橡胶垫', href: '/category/10/2' },
      ],
    },
    {
      title: '暖气片',
      children: [
        { title: '工业式暖气片', href: '/category/11/1' },
        { title: '暖气固定卡', href: '/category/11/2' },
        { title: '暖气托勾', href: '/category/11/3' },
      ],
    },
    {
      title: '铜管件',
      children: [
        { title: '铜对丝', href: '/category/12/1' },
        { title: '铜管箍', href: '/category/12/2' },
        { title: '铜三通', href: '/category/12/3' },
        { title: '铜弯头', href: '/category/12/4' },
      ],
    },
    {
      title: '焊接管件',
      children: [
        { title: '焊接大小头', href: '/category/13/1' },
        { title: '焊接弯头', href: '/category/13/2' },
        { title: '冷拔三通', href: '/category/13/3' },
      ],
    },
    {
      title: '水表及配件',
      children: [
        { title: '热水表', href: '/category/14/1' },
        { title: '数字水表', href: '/category/14/2' },
        { title: '水表垫', href: '/category/14/3' },
        { title: '水表接头', href: '/category/14/4' },
        { title: '冷水表', href: '/category/14/5' },
        { title: '法兰水表', href: '/category/14/6' },
      ],
    },
    { title: '波纹补偿器', children: [{ title: '10KG内压式补偿器', href: '/category/15/1' }] },
    {
      title: '水力自控阀',
      children: [
        { title: '先导式减压阀', href: '/category/16/1' },
        { title: '倒流防止器', href: '/category/16/2' },
        { title: '水力止回阀', href: '/category/16/3' },
        { title: '铁浮球阀', href: '/category/16/4' },
        { title: '压差控制阀', href: '/category/16/5' },
        { title: '液压水位控制阀', href: '/category/16/6' },
      ],
    },
    {
      title: '熟铁管件',
      children: [
        { title: '白熟箍', href: '/category/17/1' },
        { title: '黑熟箍', href: '/category/17/2' },
      ],
    },
    {
      title: '其他水暖',
      children: [
        { title: '不锈钢金属软管', href: '/category/18/1' },
        { title: '柔性防水套管', href: '/category/18/2' },
        { title: '铁表弯管', href: '/category/18/3' },
        { title: '橡胶软接头', href: '/category/18/4' },
        { title: '不锈钢球阀', href: '/category/18/5' },
        { title: '生料带', href: '/category/18/6' },
        { title: 'PE球阀', href: '/category/18/7' },
      ],
    },
  ],
  [
    {
      title: '光源',
      children: [
        { title: '灯带', href: '/category/1/1' },
        { title: '灯管', href: '/category/1/2' },
        { title: '灯泡', href: '/category/1/3' },
        { title: '节能灯', href: '/category/1/4' },
        { title: '平板灯', href: '/category/1/5' },
        { title: '吸顶灯', href: '/category/1/6' },
      ],
    },
    {
      title: '灯具',
      children: [
        { title: '防爆灯', href: '/category/2/1' },
        { title: '防潮灯', href: '/category/2/2' },
        { title: '工作灯', href: '/category/2/3' },
        { title: '花灯', href: '/category/2/4' },
        { title: '手电筒', href: '/category/2/5' },
        { title: '筒灯', href: '/category/2/6' },
        { title: '头灯', href: '/category/2/7' },
        { title: '投光灯', href: '/category/2/8' },
        { title: '应急灯', href: '/category/2/9' },
      ],
    },
    {
      title: '灯口',
      children: [
        { title: '瓷灯口', href: '/category/3/1' },
        { title: '防水灯口', href: '/category/3/2' },
        { title: '声光控灯口', href: '/category/3/3' },
        { title: '塑料灯口', href: '/category/3/4' },
      ],
    },
    {
      title: '室外灯具',
      children: [
        { title: '草地灯', href: '/category/4/1' },
        { title: '触发器', href: '/category/4/2' },
        { title: '景观灯', href: '/category/4/3' },
        { title: '探照灯', href: '/category/4/4' },
        { title: '镇流器', href: '/category/4/5' },
      ],
    },
    {
      title: '支架',
      children: [
        { title: '格栅灯', href: '/category/5/1' },
        { title: '支架配件', href: '/category/5/2' },
      ],
    },
    {
      title: '其他灯具',
      children: [
        { title: '碘钨灯架', href: '/category/6/1' },
        { title: '灭蚊灯', href: '/category/6/2' },
        { title: '吊链', href: '/category/6/3' },
      ],
    },
  ],
  [
    {
      title: '保温材料',
      children: [
        { title: '保温板', href: '/category/1/1' },
        { title: '保温管', href: '/category/1/2' },
        { title: '保温毛毡', href: '/category/1/3' },
        { title: '内外墙保温', href: '/category/1/4' },
        { title: '电伴热带', href: '/category/1/5' },
        { title: '保温钉', href: '/category/1/6' },
      ],
    },
    {
      title: '保温带',
      children: [
        { title: '绑扎带', href: '/category/2/1' },
        { title: '铝泊胶带', href: '/category/2/2' },
        { title: '嵌缝带', href: '/category/2/3' },
        { title: '橡塑胶带', href: '/category/2/4' },
      ],
    },
    {
      title: '防水材料',
      children: [
        { title: '防水涂料', href: '/category/3/1' },
        { title: '沥青膏', href: '/category/3/2' },
        { title: '水不漏', href: '/category/3/3' },
        { title: '油毡', href: '/category/3/4' },
        { title: '其他防水涂料', href: '/category/3/5' },
      ],
    },
    {
      title: '其他材料',
      children: [
        { title: '窗纱', href: '/category/4/1' },
        { title: '护角', href: '/category/4/2' },
        { title: '密封条', href: '/category/4/3' },
        { title: '止水带', href: '/category/4/4' },
        { title: '止水条', href: '/category/4/5' },
        { title: '彩钢瓦', href: '/category/4/6' },
        { title: '窗帘', href: '/category/4/7' },
        { title: '地毯', href: '/category/4/8' },
      ],
    },
    {
      title: '石棉制品',
      children: [
        { title: '石棉板', href: '/category/5/1' },
        { title: '石棉布', href: '/category/5/2' },
        { title: '石棉瓦', href: '/category/5/3' },
      ],
    },
    {
      title: '橡胶板',
      children: [
        { title: '绝缘胶板', href: '/category/6/1' },
        { title: '绿平胶板', href: '/category/6/2' },
        { title: '耐油胶板', href: '/category/6/3' },
      ],
    },
    {
      title: '橡胶制品',
      children: [
        { title: '黑胶管', href: '/category/7/1' },
        { title: '高压风管', href: '/category/7/2' },
      ],
    },
    {
      title: '装饰板材',
      children: [
        { title: '大理石板', href: '/category/8/1' },
        { title: '大芯板', href: '/category/8/2' },
        { title: '多层板', href: '/category/8/3' },
        { title: '硅酸钙板', href: '/category/8/4' },
        { title: '挤塑板', href: '/category/8/5' },
        { title: '石膏板', href: '/category/8/6' },
      ],
    },
    {
      title: '装饰型材',
      children: [
        { title: '龙骨', href: '/category/9/1' },
        { title: '龙骨配件', href: '/category/9/2' },
      ],
    },
  ],
  [
    {
      title: '龙头/水咀',
      children: [
        { title: '快开龙头/水咀', href: '/category/1/1' },
        { title: '面盆龙头', href: '/category/1/2' },
        { title: '直通阀', href: '/category/1/3' },
        { title: '厨盆龙头', href: '/category/1/4' },
        { title: '淋浴阀', href: '/category/1/5' },
      ],
    },
    {
      title: '冲洗阀',
      children: [
        { title: '大便冲洗阀', href: '/category/2/1' },
        { title: '小便冲洗阀', href: '/category/2/2' },
      ],
    },
    { title: '面盆', children: [{ title: '柱盆', href: '/category/3/1' }] },
    {
      title: '卫生陶瓷',
      children: [
        { title: '小便器', href: '/category/4/1' },
        { title: '座便器', href: '/category/4/2' },
        { title: '蹲便', href: '/category/4/3' },
      ],
    },
    { title: '感应器', children: [{ title: '小便感应器', href: '/category/5/1' }] },
    {
      title: '其他卫浴',
      children: [
        { title: '热水器', href: '/category/6/1' },
        { title: '拖布池', href: '/category/6/2' },
        { title: '洗槽', href: '/category/6/3' },
      ],
    },
    {
      title: '洁具配件',
      children: [
        { title: '花洒', href: '/category/7/1' },
        { title: '软管', href: '/category/7/2' },
        { title: '塑料洁具', href: '/category/7/3' },
        { title: '下水口', href: '/category/7/4' },
        { title: '地漏', href: '/category/7/5' },
      ],
    },
  ],
  [
    {
      title: '管材',
      children: [
        { title: '焊管', href: '/category/1/1' },
        { title: '衬塑管', href: '/category/1/2' },
        { title: '方管', href: '/category/1/3' },
        { title: '热管/镀锌管', href: '/category/1/4' },
        { title: '无缝管', href: '/category/1/5' },
      ],
    },
    {
      title: '板材',
      children: [
        { title: '镀锌板', href: '/category/2/1' },
        { title: '花纹板', href: '/category/2/2' },
        { title: '围挡板', href: '/category/2/3' },
        { title: '中板', href: '/category/2/4' },
        { title: '冷板', href: '/category/2/5' },
      ],
    },
    {
      title: '型材',
      children: [
        { title: '槽钢', href: '/category/3/1' },
        { title: '工字钢', href: '/category/3/2' },
        { title: '热镀锌扁铁', href: '/category/3/3' },
        { title: '热镀锌槽钢', href: '/category/3/4' },
        { title: '角铁', href: '/category/3/5' },
        { title: '热镀锌圆钢', href: '/category/3/6' },
      ],
    },
  ],
  [
    {
      title: '油漆',
      children: [
        { title: '醇酸调和漆', href: '/category/1/1' },
        { title: '防锈漆', href: '/category/1/2' },
        { title: '环氧漆', href: '/category/1/3' },
        { title: '银粉漆', href: '/category/1/4' },
        { title: '自喷漆', href: '/category/1/5' },
        { title: '稀释剂', href: '/category/1/6' },
      ],
    },
    {
      title: '特种漆',
      children: [
        { title: '沥青漆', href: '/category/2/1' },
        { title: '烟囱漆', href: '/category/2/2' },
      ],
    },
    {
      title: '涂料',
      children: [
        { title: '精家装涂料', href: '/category/3/1' },
        { title: '工程涂料', href: '/category/3/2' },
      ],
    },
    {
      title: '腻子',
      children: [
        { title: '821腻子', href: '/category/4/1' },
        { title: '耐水腻子', href: '/category/4/2' },
        { title: '柔韧腻子', href: '/category/4/3' },
        { title: '透明腻子', href: '/category/4/4' },
        { title: '原子灰', href: '/category/4/5' },
      ],
    },
    {
      title: '密封材料',
      children: [
        { title: '密封胶', href: '/category/5/1' },
        { title: '发泡胶', href: '/category/5/2' },
        { title: '酸性胶', href: '/category/5/3' },
        { title: '中性胶', href: '/category/5/4' },
      ],
    },
    {
      title: '粘合剂',
      children: [
        { title: '白乳胶', href: '/category/6/1' },
        { title: '万能胶', href: '/category/6/2' },
        { title: '云石胶', href: '/category/6/3' },
      ],
    },
    {
      title: '防火材料',
      children: [
        { title: '防火堵料', href: '/category/7/1' },
        { title: '防火毯', href: '/category/7/2' },
        { title: '防火涂料', href: '/category/7/3' },
        { title: '防火枕', href: '/category/7/4' },
      ],
    },
    {
      title: '粉刷石膏粉',
      children: [
        { title: '粉刷石膏', href: '/category/8/1' },
        { title: '嵌缝石膏', href: '/category/8/2' },
      ],
    },
    {
      title: '添加剂',
      children: [
        { title: '108胶', href: '/category/9/1' },
        { title: '903胶', href: '/category/9/2' },
        { title: '瓷砖胶', href: '/category/9/3' },
        { title: '混凝土外加剂', href: '/category/9/4' },
        { title: '界面剂', href: '/category/9/5' },
        { title: '快粘粉', href: '/category/9/6' },
      ],
    },
    {
      title: '其他溶剂、辅材',
      children: [
        { title: '松动剂', href: '/category/10/1' },
        { title: '白水泥', href: '/category/10/2' },
        { title: '玻璃水', href: '/category/10/3' },
        { title: '草酸水', href: '/category/10/4' },
        { title: '柴机油', href: '/category/10/5' },
        { title: '齿轮油', href: '/category/10/6' },
        { title: '大白粉', href: '/category/10/7' },
        { title: '敌敌畏', href: '/category/10/8' },
        { title: '防冻液', href: '/category/10/9' },
        { title: '粉', href: '/category/10/10' },
        { title: '工业酒精', href: '/category/10/11' },
        { title: '固化剂', href: '/category/10/12' },
        { title: '滑石粉', href: '/category/10/13' },
        { title: '环氧树脂', href: '/category/10/14' },
        { title: '火碱', href: '/category/10/15' },
        { title: '金刚砂', href: '/category/10/16' },
        { title: '煤油', href: '/category/10/17' },
        { title: '硼砂', href: '/category/10/18' },
        { title: '切削液', href: '/category/10/19' },
        { title: '融雪剂', href: '/category/10/20' },
        { title: '润滑脂', href: '/category/10/21' },
        { title: '疏通液', href: '/category/10/22' },
        { title: '松香块', href: '/category/10/23' },
        { title: '脱模剂', href: '/category/10/24' },
      ],
    },
  ],
  [
    {
      title: '测绘工具',
      children: [
        { title: '经纬仪', href: '/category/1/1' },
        { title: '标线仪', href: '/category/1/2' },
        { title: '测量绳', href: '/category/1/3' },
        { title: '检测尺', href: '/category/1/4' },
        { title: '铝合金花杆', href: '/category/1/5' },
        { title: '铝合金塔尺', href: '/category/1/6' },
        { title: '三角架', href: '/category/1/7' },
        { title: '水准仪', href: '/category/1/8' },
        { title: '探测仪', href: '/category/1/9' },
        { title: '测距仪', href: '/category/1/10' },
      ],
    },
    {
      title: '电动工具',
      children: [
        { title: '冲击钻', href: '/category/2/1' },
        { title: '吹风机', href: '/category/2/2' },
        { title: '磁力钻', href: '/category/2/3' },
        { title: '打磨机', href: '/category/2/4' },
        { title: '电扳手', href: '/category/2/5' },
        { title: '电锤', href: '/category/2/6' },
        { title: '电动空压机', href: '/category/2/7' },
        { title: '电动试压泵', href: '/category/2/8' },
        { title: '电镐', href: '/category/2/9' },
        { title: '电剪刀', href: '/category/2/10' },
        { title: '电链锯', href: '/category/2/11' },
        { title: '电磨', href: '/category/2/12' },
        { title: '电刨', href: '/category/2/13' },
        { title: '电圆锯', href: '/category/2/14' },
        { title: '电钻', href: '/category/2/15' },
        { title: '雕刻机', href: '/category/2/16' },
        { title: '角磨机', href: '/category/2/17' },
        { title: '锯铝机', href: '/category/2/18' },
        { title: '开槽机', href: '/category/2/19' },
        { title: '抛光机', href: '/category/2/20' },
        { title: '抛光轮', href: '/category/2/21' },
        { title: '曲线锯', href: '/category/2/22' },
        { title: '热风枪', href: '/category/2/23' },
        { title: '砂带机', href: '/category/2/24' },
        { title: '水钻机', href: '/category/2/25' },
        { title: '往复锯', href: '/category/2/26' },
        { title: '修边机', href: '/category/2/27' },
        { title: '云石机', href: '/category/2/28' },
        { title: '其他电动工具', href: '/category/2/29' },
        { title: '电动搅拌机', href: '/category/2/30' },
      ],
    },
    {
      title: '工具配件/耗材',
      children: [
        { title: '不锈钢拉丝布', href: '/category/3/1' },
        { title: '冲击钻头', href: '/category/3/2' },
        { title: '弹性磨盘', href: '/category/3/3' },
        { title: '电锤钻头', href: '/category/3/4' },
        { title: '电磨头', href: '/category/3/5' },
        { title: '钢丝轮', href: '/category/3/6' },
        { title: '钢丝刷', href: '/category/3/7' },
        { title: '镐钎', href: '/category/3/8' },
        { title: '工具配件其它', href: '/category/3/9' },
        { title: '合金锯片', href: '/category/3/10' },
        { title: '角磨片', href: '/category/3/11' },
        { title: '绞板、板牙', href: '/category/3/12' },
        { title: '锯条', href: '/category/3/13' },
        { title: '开孔器', href: '/category/3/14' },
        { title: '空压机配件', href: '/category/3/15' },
        { title: '马路切割片', href: '/category/3/16' },
        { title: '马路用具', href: '/category/3/17' },
        { title: '沙盘纸', href: '/category/3/18' },
        { title: '砂轮片', href: '/category/3/19' },
        { title: '砂纸、砂布', href: '/category/3/20' },
        { title: '树脂切割片', href: '/category/3/21' },
        { title: '水钻头', href: '/category/3/22' },
        { title: '陶瓷切割片', href: '/category/3/23' },
        { title: '套丝机配件', href: '/category/3/24' },
        { title: '云石片', href: '/category/3/25' },
        { title: '电动工具配件', href: '/category/3/26' },
      ],
    },
    {
      title: '管工工具',
      children: [
        { title: '沟槽机', href: '/category/4/1' },
        { title: '沟槽机配件', href: '/category/4/2' },
        { title: '管钳', href: '/category/4/3' },
        { title: '管子割刀', href: '/category/4/4' },
        { title: '开孔刀', href: '/category/4/5' },
        { title: '切管机', href: '/category/4/6' },
        { title: '切管机配件', href: '/category/4/7' },
        { title: '套丝机', href: '/category/4/8' },
        { title: '弯管器', href: '/category/4/9' },
        { title: '压力钳\\钳牙', href: '/category/4/10' },
      ],
    },
    {
      title: '量具刃具',
      children: [
        { title: '秤', href: '/category/5/1' },
        { title: '锉类', href: '/category/5/2' },
        { title: '钢直尺、角尺', href: '/category/5/3' },
        { title: '卷尺', href: '/category/5/4' },
        { title: '麻花钻头', href: '/category/5/5' },
        { title: '千分尺', href: '/category/5/6' },
        { title: '塞尺', href: '/category/5/7' },
        { title: '手用/机用丝锥', href: '/category/5/8' },
        { title: '水平尺', href: '/category/5/9' },
        { title: '铣刀', href: '/category/5/10' },
        { title: '游标卡尺', href: '/category/5/11' },
        { title: '锥柄钻套', href: '/category/5/12' },
      ],
    },
    {
      title: '喷涂工具',
      children: [
        { title: '滚刷', href: '/category/6/1' },
        { title: '喷浆机', href: '/category/6/2' },
        { title: '喷枪', href: '/category/6/3' },
        { title: '羊毛刷', href: '/category/6/4' },
        { title: '油漆刷', href: '/category/6/5' },
      ],
    },
    {
      title: '起重工具',
      children: [
        { title: '吊装带', href: '/category/7/1' },
        { title: '钢丝绳', href: '/category/7/2' },
        { title: '花兰螺丝', href: '/category/7/3' },
        { title: '鸡心环', href: '/category/7/4' },
        { title: '卡头', href: '/category/7/5' },
        { title: '起重吊钳', href: '/category/7/6' },
        { title: '起重葫芦', href: '/category/7/7' },
        { title: '起重滑车', href: '/category/7/8' },
        { title: '千斤顶', href: '/category/7/9' },
        { title: '千斤顶配件', href: '/category/7/10' },
        { title: '牵引器', href: '/category/7/11' },
        { title: '手摇绞车', href: '/category/7/12' },
        { title: '手摇垮顶', href: '/category/7/13' },
        { title: '天地轮', href: '/category/7/14' },
        { title: '卸甲', href: '/category/7/15' },
      ],
    },
    {
      title: '气动工具',
      children: [
        { title: '钉枪', href: '/category/8/1' },
        { title: '风炮', href: '/category/8/2' },
        { title: '风批', href: '/category/8/3' },
        { title: '空压机', href: '/category/8/4' },
        { title: '储气罐', href: '/category/8/5' },
        { title: '风镐', href: '/category/8/6' },
        { title: '其他气动工具', href: '/category/8/7' },
        { title: '气锤', href: '/category/8/8' },
        { title: '气动黄油枪', href: '/category/8/9' },
      ],
    },
    {
      title: '实验器材',
      children: [
        { title: '测试仪', href: '/category/9/1' },
        { title: '刮板', href: '/category/9/2' },
        { title: '烘干箱', href: '/category/9/3' },
        { title: '敲击工具', href: '/category/9/4' },
        { title: '试模', href: '/category/9/5' },
        { title: '试验棒', href: '/category/9/6' },
        { title: '试验烧杯', href: '/category/9/7' },
        { title: '坍落度', href: '/category/9/8' },
        { title: '探测仪', href: '/category/9/9' },
        { title: '脱模剂', href: '/category/9/10' },
        { title: '温湿度计', href: '/category/9/11' },
        { title: '养护室', href: '/category/9/12' },
        { title: '振动器', href: '/category/9/13' },
      ],
    },
    {
      title: '手动工具',
      children: [
        { title: '扳手类', href: '/category/10/1' },
        { title: '工具包/箱/车', href: '/category/10/2' },
        { title: '活扳手', href: '/category/10/3' },
        { title: '棘轮扳手', href: '/category/10/4' },
        { title: '剪切工具', href: '/category/10/5' },
        { title: '其他手动工具', href: '/category/10/6' },
        { title: '钳类', href: '/category/10/7' },
        { title: '敲击工具', href: '/category/10/8' },
        { title: '套筒及配件', href: '/category/10/9' },
        { title: '旋具类', href: '/category/10/10' },
        { title: '组套工具', href: '/category/10/11' },
        { title: '开口扳手', href: '/category/10/12' },
        { title: '鲤鱼钳', href: '/category/10/13' },
        { title: '两用扳手', href: '/category/10/14' },
        { title: '梅花扳手', href: '/category/10/15' },
        { title: '扭力扳手', href: '/category/10/16' },
      ],
    },
    {
      title: '瓦木工具',
      children: [
        { title: '大铲', href: '/category/11/1' },
        { title: '斧子', href: '/category/11/2' },
        { title: '刮板', href: '/category/11/3' },
        { title: '抹子', href: '/category/11/4' },
        { title: '墨斗', href: '/category/11/5' },
        { title: '墨汁', href: '/category/11/6' },
        { title: '木工刨子', href: '/category/11/7' },
        { title: '木工手锯', href: '/category/11/8' },
        { title: '内外角', href: '/category/11/9' },
        { title: '刨奔', href: '/category/11/10' },
        { title: '托灰板', href: '/category/11/11' },
        { title: '瓦刀', href: '/category/11/12' },
        { title: '线坠', href: '/category/11/13' },
        { title: '油灰刀', href: '/category/11/14' },
      ],
    },
    { title: '液压工具', children: [{ title: '液压钢筋剪', href: '/category/12/1' }] },
    { title: '园林工具', children: [{ title: '油锯', href: '/category/13/1' }] },
  ],
  [
    {
      title: '地脚螺栓',
      children: [
        { title: '双头栓', href: '/category/1/1' },
        { title: 'L型地脚', href: '/category/1/2' },
        { title: '镀锌双头栓', href: '/category/1/3' },
      ],
    },
    {
      title: '钉子类',
      children: [
        { title: '搓丝钉', href: '/category/2/1' },
        { title: '地板钉', href: '/category/2/2' },
        { title: '钢排钉', href: '/category/2/3' },
        { title: '钢丝', href: '/category/2/4' },
        { title: '卷钉', href: '/category/2/5' },
        { title: '码钉', href: '/category/2/6' },
        { title: '汽钉', href: '/category/2/7' },
        { title: '射弹', href: '/category/2/8' },
        { title: '射钉', href: '/category/2/9' },
        { title: '水泥钉', href: '/category/2/10' },
        { title: '蚊钉', href: '/category/2/11' },
        { title: '元钉', href: '/category/2/12' },
      ],
    },
    {
      title: '发电机',
      children: [
        { title: '汽油发电机', href: '/category/3/1' },
        { title: '柴油发电机', href: '/category/3/2' },
      ],
    },
    {
      title: '钢结构螺栓',
      children: [
        { title: '10.9级钢结构螺栓', href: '/category/4/1' },
        { title: '10级钢结构螺母', href: '/category/4/2' },
        { title: '花兰螺栓', href: '/category/4/3' },
      ],
    },
    {
      title: '高强度螺栓',
      children: [
        { title: '8.8级螺栓', href: '/category/5/1' },
        { title: '8级螺母', href: '/category/5/2' },
        { title: '镀锌螺母', href: '/category/5/3' },
      ],
    },
    {
      title: '紧固件其他',
      children: [
        { title: '标准扣件', href: '/category/6/1' },
        { title: '步步紧', href: '/category/6/2' },
        { title: '钢筋接头', href: '/category/6/3' },
        { title: '钢筋马镫', href: '/category/6/4' },
        { title: '钢筋网片', href: '/category/6/5' },
        { title: '环槽铆钉', href: '/category/6/6' },
        { title: '环眼吊钩', href: '/category/6/7' },
        { title: '马鞍垫', href: '/category/6/8' },
        { title: '平铝铆钉', href: '/category/6/9' },
        { title: '山型件', href: '/category/6/10' },
        { title: '山型母', href: '/category/6/11' },
        { title: '锁紧母', href: '/category/6/12' },
        { title: '梯形丝杆', href: '/category/6/13' },
        { title: '预埋钢板', href: '/category/6/14' },
        { title: '元锥体', href: '/category/6/15' },
        { title: '止水钢板', href: '/category/6/16' },
      ],
    },
    {
      title: '捆绑辅材',
      children: [
        { title: '火烧丝', href: '/category/7/1' },
        { title: '铅丝/铁丝', href: '/category/7/2' },
      ],
    },
    {
      title: '螺栓垫片',
      children: [
        { title: '弹垫', href: '/category/8/1' },
        { title: '平垫', href: '/category/8/2' },
        { title: '高强度平垫', href: '/category/8/3' },
        { title: '鱼眼垫', href: '/category/8/4' },
      ],
    },
    {
      title: '螺栓螺母',
      children: [
        { title: '4.8级光母', href: '/category/9/1' },
        { title: '4.8级光栓', href: '/category/9/2' },
        { title: '4.8级螺母', href: '/category/9/3' },
        { title: '4.8级锌母', href: '/category/9/4' },
        { title: '4.8级螺栓', href: '/category/9/5' },
        { title: '4.8级锌栓', href: '/category/9/6' },
      ],
    },
    {
      title: '锚栓植筋胶',
      children: [
        { title: '化学锚栓', href: '/category/10/1' },
        { title: '机械锚栓', href: '/category/10/2' },
        { title: '植筋胶', href: '/category/10/3' },
      ],
    },
    {
      title: '铆钉',
      children: [
        { title: 'F型拉铆钉', href: '/category/11/1' },
        { title: '拉铆钉', href: '/category/11/2' },
        { title: '平锌铆钉', href: '/category/11/3' },
      ],
    },
    { title: '内胀', children: [{ title: '内胀套管', href: '/category/12/1' }] },
    {
      title: '其他五金',
      children: [
        { title: '门窗配件', href: '/category/13/1' },
        { title: '保险勾', href: '/category/13/2' },
        { title: '镀锌铁链', href: '/category/13/3' },
        { title: '工具平板车', href: '/category/13/4' },
        { title: '尼龙轮', href: '/category/13/5' },
        { title: '塔吊料斗', href: '/category/13/6' },
        { title: '预应力锚具', href: '/category/13/7' },
      ],
    },
    {
      title: '丝网',
      children: [
        { title: '窗纱', href: '/category/14/1' },
        { title: '刺绳', href: '/category/14/2' },
        { title: '地暖网', href: '/category/14/3' },
        { title: '镀锌电焊网', href: '/category/14/4' },
        { title: '镀锌六角网', href: '/category/14/5' },
        { title: '镀锌美格网', href: '/category/14/6' },
        { title: '钢板网', href: '/category/14/7' },
        { title: '筛子底', href: '/category/14/8' },
        { title: '收口网', href: '/category/14/9' },
      ],
    },
    {
      title: '锁类',
      children: [
        { title: '搬把锁', href: '/category/15/1' },
        { title: '抽屉锁', href: '/category/15/2' },
        { title: '防撬锁', href: '/category/15/3' },
        { title: '挂锁', href: '/category/15/4' },
        { title: '链锁', href: '/category/15/5' },
        { title: '碰锁', href: '/category/15/6' },
        { title: '球型门锁', href: '/category/15/7' },
      ],
    },
    {
      title: '小型机械',
      children: [
        { title: '雾炮机', href: '/category/16/1' },
        { title: '呼叫器', href: '/category/16/2' },
        { title: '清洗机/洗车机', href: '/category/16/3' },
        { title: '管道疏通机', href: '/category/16/4' },
        { title: '管道疏通机配件', href: '/category/16/5' },
        { title: '台式砂轮机', href: '/category/16/6' },
        { title: '吸尘吸水机', href: '/category/16/7' },
      ],
    },
    {
      title: '锌丝杆/母',
      children: [
        { title: '六角连接母', href: '/category/17/1' },
        { title: '锌丝杆', href: '/category/17/2' },
      ],
    },
    {
      title: '胀栓胀塞',
      children: [
        { title: '胀栓', href: '/category/18/1' },
        { title: '多功能拉爆', href: '/category/18/2' },
        { title: '塑料胀塞', href: '/category/18/3' },
      ],
    },
    { title: '轴承三角带', children: [{ title: '轴承', href: '/category/19/1' }] },
    {
      title: '钻攻螺钉',
      children: [
        { title: '自攻丝', href: '/category/20/1' },
        { title: '自钻丝', href: '/category/20/2' },
        { title: '自钻丝防水帽', href: '/category/20/3' },
        { title: '自钻丝套头', href: '/category/20/4' },
        { title: '纤维板钉', href: '/category/20/5' },
      ],
    },
  ],
  [
    {
      title: '风管及接头',
      children: [
        { title: '铝合金风管', href: '/category/1/1' },
        { title: '塑料通风管', href: '/category/1/2' },
      ],
    },
    {
      title: '灭火器',
      children: [
        { title: 'ABC灭火器', href: '/category/2/1' },
        { title: '灭火器配件', href: '/category/2/2' },
        { title: '水基型灭火器', href: '/category/2/3' },
        { title: '二氧化碳灭火器', href: '/category/2/4' },
      ],
    },
    {
      title: '喷淋系统',
      children: [
        { title: '湿式报警器', href: '/category/3/1' },
        { title: '水流指示器', href: '/category/3/2' },
        { title: '消防报警器', href: '/category/3/3' },
        { title: '消防喷头', href: '/category/3/4' },
      ],
    },
    {
      title: '其他消防通风',
      children: [
        { title: '不锈钢空调波纹管', href: '/category/4/1' },
        { title: '测试工具', href: '/category/4/2' },
        { title: '风管接头', href: '/category/4/3' },
        { title: '风口', href: '/category/4/4' },
        { title: '阻火圈', href: '/category/4/5' },
        { title: '风道阀门', href: '/category/4/6' },
        { title: '水泵接合器', href: '/category/4/7' },
        { title: '风机、换气扇', href: '/category/4/8' },
      ],
    },
    {
      title: '水带',
      children: [
        { title: '工程水带', href: '/category/5/1' },
        { title: '兰水带', href: '/category/5/2' },
        { title: '消防卷盘', href: '/category/5/3' },
        { title: '消防水带', href: '/category/5/4' },
      ],
    },
    {
      title: '水枪/接扣',
      children: [
        { title: '兰水带接扣', href: '/category/6/1' },
        { title: '消防接扣', href: '/category/6/2' },
        { title: '消防水枪', href: '/category/6/3' },
        { title: '消防卡箍', href: '/category/6/4' },
      ],
    },
    {
      title: '消防工具',
      children: [
        { title: '消防桶', href: '/category/7/1' },
        { title: '消火栓扳手', href: '/category/7/2' },
        { title: '标志牌', href: '/category/7/3' },
        { title: '消防锹', href: '/category/7/4' },
        { title: '消防勾', href: '/category/7/5' },
        { title: '消防斧', href: '/category/7/6' },
        { title: '灭火毯', href: '/category/7/7' },
      ],
    },
    {
      title: '消防架',
      children: [
        { title: '单框消防架', href: '/category/8/1' },
        { title: '双框消防架', href: '/category/8/2' },
      ],
    },
    {
      title: '消防箱',
      children: [
        { title: '铝合金玻璃门箱', href: '/category/9/1' },
        { title: '灭火器箱', href: '/category/9/2' },
        { title: '消防铁栓箱', href: '/category/9/3' },
        { title: '消防箱玻璃', href: '/category/9/4' },
      ],
    },
    {
      title: '消火栓',
      children: [
        { title: '室内消火栓', href: '/category/10/1' },
        { title: '室外地下栓', href: '/category/10/2' },
      ],
    },
  ],
  [
    {
      title: '水泵',
      children: [
        { title: '污水泵', href: '/category/1/1' },
        { title: '管道泵', href: '/category/1/2' },
        { title: '暖气循环泵', href: '/category/1/3' },
        { title: '潜水泵', href: '/category/1/4' },
        { title: '水泵配件', href: '/category/1/5' },
        { title: '增压泵', href: '/category/1/6' },
        { title: '自吸泵', href: '/category/1/7' },
      ],
    },
  ],
  [
    {
      title: '办公用纸',
      children: [
        { title: '普通复印纸', href: '/category/1/1' },
        { title: '相片纸', href: '/category/1/2' },
        { title: '电脑打印纸', href: '/category/1/3' },
        { title: '收银纸', href: '/category/1/4' },
        { title: '传真纸', href: '/category/1/5' },
        { title: '牛皮纸', href: '/category/1/6' },
        { title: '其他纸', href: '/category/1/7' },
      ],
    },
    {
      title: '办公耗材',
      children: [
        { title: '墨盒', href: '/category/2/1' },
        { title: '硒鼓', href: '/category/2/2' },
        { title: '墨粉', href: '/category/2/3' },
        { title: '色带', href: '/category/2/4' },
        { title: '其他耗材', href: '/category/2/5' },
      ],
    },
    {
      title: '办公文具',
      children: [
        { title: '笔', href: '/category/3/1' },
        { title: '笔芯', href: '/category/3/2' },
        { title: '墨水/墨汁/补充液', href: '/category/3/3' },
        { title: '修正用品', href: '/category/3/4' },
        { title: '文件盒/袋/夹/架/包', href: '/category/3/5' },
        { title: '资料册', href: '/category/3/6' },
        { title: '票据包（册）', href: '/category/3/7' },
        { title: '名片册/盒/夹', href: '/category/3/8' },
        { title: '本册纸品', href: '/category/3/9' },
        { title: '桌面文具', href: '/category/3/10' },
        { title: '财务行政用品', href: '/category/3/11' },
        { title: '会议展示用品', href: '/category/3/12' },
      ],
    },
    {
      title: '办公设备',
      children: [
        { title: '打印机', href: '/category/4/1' },
        { title: '多功能一体机', href: '/category/4/2' },
        { title: '传真机', href: '/category/4/3' },
        { title: '复印机', href: '/category/4/4' },
        { title: '演示设备', href: '/category/4/5' },
        { title: '财务行政设备', href: '/category/4/6' },
      ],
    },
    {
      title: 'IT/数码/通讯/家电',
      children: [
        { title: '电脑整机', href: '/category/5/1' },
        { title: '电脑外设', href: '/category/5/2' },
        { title: '电脑配件', href: '/category/5/3' },
        { title: '存储设备', href: '/category/5/4' },
        { title: '网络设备', href: '/category/5/5' },
        { title: '影像设备', href: '/category/5/6' },
        { title: '通讯设备', href: '/category/5/7' },
        { title: '办公家电', href: '/category/5/8' },
      ],
    },
    {
      title: '办公日杂',
      children: [
        { title: '生活用纸', href: '/category/6/1' },
        { title: '清洁用品', href: '/category/6/2' },
        { title: '洗护用品', href: '/category/6/3' },
        { title: '一次性用品', href: '/category/6/4' },
        { title: '日常用品', href: '/category/6/5' },
        { title: '运动休闲用品', href: '/category/6/6' },
        { title: '医护用品', href: '/category/6/7' },
        { title: '食品饮料', href: '/category/6/8' },
        { title: '床品套件', href: '/category/6/9' },
      ],
    },
    {
      title: '办公家具',
      children: [
        { title: '座椅', href: '/category/7/1' },
        { title: '桌台', href: '/category/7/2' },
        { title: '储物柜', href: '/category/7/3' },
        { title: '床', href: '/category/7/4' },
      ],
    },
  ],
  [
    {
      title: '门禁设备',
      children: [
        { title: 'IC卡', href: '/category/1/1' },
        { title: '发卡器', href: '/category/1/2' },
        { title: 'IC卡刷卡感应器', href: '/category/1/3' },
        { title: '身份证阅读器', href: '/category/1/4' },
        { title: '电脑', href: '/category/1/5' },
        { title: '集装箱', href: '/category/1/6' },
        { title: '稳压器', href: '/category/1/7' },
        { title: '摄像头（门禁专用）', href: '/category/1/8' },
        { title: '门禁控制器', href: '/category/1/9' },
        { title: '液晶电视', href: '/category/1/10' },
        { title: '闸机', href: '/category/1/11' },
        { title: '显示器（门禁系统）', href: '/category/1/12' },
        { title: '三辊闸', href: '/category/1/13' },
        { title: '翼闸', href: '/category/1/14' },
        { title: '摆闸', href: '/category/1/15' },
        { title: 'IC卡全高转闸', href: '/category/1/16' },
        { title: '交换机（门禁专用）', href: '/category/1/17' },
      ],
    },
    {
      title: '收验货设备',
      children: [
        { title: '机柜', href: '/category/2/1' },
        { title: '工控机', href: '/category/2/2' },
        { title: '显示器', href: '/category/2/3' },
        { title: '针式打印机', href: '/category/2/4' },
        { title: '高拍仪', href: '/category/2/5' },
        { title: '高清摄像头（收验货专用）', href: '/category/2/6' },
        { title: '硬盘录像机', href: '/category/2/7' },
        { title: '硬盘', href: '/category/2/8' },
        { title: '杆件', href: '/category/2/9' },
        { title: '高杆件', href: '/category/2/10' },
        { title: '钢构称台', href: '/category/2/11' },
        { title: '数字称重仪表', href: '/category/2/12' },
        { title: '数字称重传感器', href: '/category/2/13' },
        { title: '不锈钢接线盒', href: '/category/2/14' },
        { title: '车牌识别摄像头加LED补光灯', href: '/category/2/15' },
        { title: '道闸', href: '/category/2/16' },
        { title: '地感线圈', href: '/category/2/17' },
        { title: '多光束开关保护罩', href: '/category/2/18' },
        { title: '光电开关保护罩', href: '/category/2/19' },
        { title: '显示器（显示系统）', href: '/category/2/20' },
        { title: '显示器（视频监控）', href: '/category/2/21' },
      ],
    },
  ],
];
